#!/bin/sh

/bin/busybox --install -s /bin

mount -t proc none /proc
mount -t sysfs none /sys

echo "===== Hello from Mirko's /init =====" > /dev/console

uname -a
echo "PATH=$PATH"

exec /bin/busybox sh

